"""initial

Revision ID: 1c861d0e0b8
Revises: None
Create Date: 2015-05-24 09:56:23.210042

"""

# revision identifiers, used by Alembic.
revision = '1c861d0e0b8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('fruit',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('contains_seeds', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vegetable',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vegetable')
    op.drop_table('fruit')
    op.drop_table('users')
    op.drop_table('food')
    ### end Alembic commands ###